/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellsRouteImport } from './routes/sells'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RawMaterialRouteImport } from './routes/raw-material'
import { Route as PcEntriesRouteImport } from './routes/pc-entries'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'

const SellsRoute = SellsRouteImport.update({
  id: '/sells',
  path: '/sells',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RawMaterialRoute = RawMaterialRouteImport.update({
  id: '/raw-material',
  path: '/raw-material',
  getParentRoute: () => rootRouteImport,
} as any)
const PcEntriesRoute = PcEntriesRouteImport.update({
  id: '/pc-entries',
  path: '/pc-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/pc-entries': typeof PcEntriesRoute
  '/raw-material': typeof RawMaterialRoute
  '/reports': typeof ReportsRoute
  '/sells': typeof SellsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/pc-entries': typeof PcEntriesRoute
  '/raw-material': typeof RawMaterialRoute
  '/reports': typeof ReportsRoute
  '/sells': typeof SellsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/pc-entries': typeof PcEntriesRoute
  '/raw-material': typeof RawMaterialRoute
  '/reports': typeof ReportsRoute
  '/sells': typeof SellsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/maintenance'
    | '/pc-entries'
    | '/raw-material'
    | '/reports'
    | '/sells'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/maintenance'
    | '/pc-entries'
    | '/raw-material'
    | '/reports'
    | '/sells'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/maintenance'
    | '/pc-entries'
    | '/raw-material'
    | '/reports'
    | '/sells'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PcEntriesRoute: typeof PcEntriesRoute
  RawMaterialRoute: typeof RawMaterialRoute
  ReportsRoute: typeof ReportsRoute
  SellsRoute: typeof SellsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sells': {
      id: '/sells'
      path: '/sells'
      fullPath: '/sells'
      preLoaderRoute: typeof SellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-material': {
      id: '/raw-material'
      path: '/raw-material'
      fullPath: '/raw-material'
      preLoaderRoute: typeof RawMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc-entries': {
      id: '/pc-entries'
      path: '/pc-entries'
      fullPath: '/pc-entries'
      preLoaderRoute: typeof PcEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  MaintenanceRoute: MaintenanceRoute,
  PcEntriesRoute: PcEntriesRoute,
  RawMaterialRoute: RawMaterialRoute,
  ReportsRoute: ReportsRoute,
  SellsRoute: SellsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
